/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_vove7_paramregex_ParamRegex */

#ifndef _Included_cn_vove7_paramregex_ParamRegex
#define _Included_cn_vove7_paramregex_ParamRegex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_vove7_paramregex_ParamRegex
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jlong JNICALL Java_cn_vove7_paramregex_ParamRegex_init
        (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_vove7_paramregex_ParamRegex
 * Method:    match
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_cn_vove7_paramregex_ParamRegex_match
        (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
